### PR TITLE
Unravel with path length window

### PR DESCRIPTION
**Pull request by arnaudon**
The unravel algorithm uses a number of points to set the window size, but this will produce an inconsistent unraveling along branches if the points are not uniformly spaced. 

In this PR, we introduce an option to use path lengths to set the window size, where the size of the windows has the number of points closest to the expected window size.

Also, near the ends of the section, the window size remains the same, and the segment to be unravelled is at the beginning (resp. end) of the window.

### CODE REVIEW

**Comment by arnaudon** [comment]
There is some weirdness of different results with different python version... @adrien-berchet , I'm sure you can find out what's wrong ;P

**Comment by arnaudon** [comment]
I don't get this bug with py37, if I drop it from the list py38 crashes the same way. Both work on bb5...

**Comment by arnaudon** [comment]
May the CI be with me!

**Comment by adrien-berchet** [comment]
:tada:

**Comment by arnaudon** [comment]
In fact, as this is breaking change, I will add an option to get the original code, otherwise we'll loose it.

**Comment by arnaudon** [comment]
@wizmer , all good for me here!

**Review by wizmer — APPROVED** [review]
LGTM!

**Comment by arnaudon** [comment]
Thanks! But I cannot merge, I don't have write access ;)

**Pull request merged**
