### PR TITLE
Sanitize with optional inhomogeneous check

### PR DESCRIPTION
**Pull request by eleftherioszisis**
Provides the option to disable the inhomogeneous neurites check in sanitization. (#96)

### CODE REVIEW

**Comment by arnaudon** [comment]
I'm not sure this is a good idea, if this is not handled properly in other codes. At least here (for the few using this function) there will be a clear warning sign. If you want to merge that quickly, I would keep the check, but if this option is on, I would only raise a warning and let it pass. Otherwise, I'll wait to sort it out globally, then adapt this function so it matches whatever implementation of this axon on dendrite will be decided.

**Comment by eleftherioszisis** [comment]
> If you want to merge that quickly

Not at all. This is PR was mainly to probe for requirements and open a discussion. Think of it as a first draft.

> I'm not sure this is a good idea, if this is not handled properly in other codes.

Would you elaborate a bit more on this? The default usage in which `allow_inhomogeneous_trees=False` is identical to how it was used before this change.

> At least here (for the few using this function) there will be a clear warning sign.

Not sure I understand this bit. Do you want to emit a warning when inhomogeneous trees are encountered? Before this change there would be a `CorruptedMorphology` error if `sanitize` was run on an inhomogeneous morphology. For `sanitize_all` it would just drop that file in which the error was raised. But it is an error, nevertheless.

> Otherwise, I'll wait to sort it out globally, then adapt this function so it matches whatever implementation of this axon on dendrite will be decided.

Keep in mind that we shouldn't be too neuron-centric because there are other types of cells too. This is why I opted for a generic `allow_inhomogeneous_trees` flag instead of something more specific. However, if NeuroR is strictly destined for neurons, then it would make sense to be more specific and check for the `axon_on_dendrite` type and let only that mixed tree pass.

**Comment by arnaudon** [comment]
1. ok!
2. my line implies: if you allow to bypass it, people will use it, then it won't be compatible with other tools. If I understood well (@mgeplf could confirm), this sanitize function was meant to be a non-optional/non-configurable one, that everybody has to 'pass' before using morphologies. If we start having options for each thing it does, it's better not to have it, and call the various checks/sanitize by hand depending on usecases (which we can still do if we want).
3. from 2., if somebody has this flag=True in a code, forget it, and has morphologies which would crash, it would go un-noticed, and maybe the axon will disappear (or whatever may happen later). I think this new flag=True, should just convert the raise to a warning, as it is still dangerous to have such morphologies atm
4. no no, generic is fine, I was just referring to the other discussion

**Comment by eleftherioszisis** [comment]
>  if you allow to bypass it, people will use it, then it won't be compatible with other tools.

Indeed, but that's the purpose of the flag, to begin with, isn't it? If someone would like to work with mixed trees then it would make sense for this check to be optional.

> If I understood well (@mgeplf could confirm), this sanitize function was meant to be a non-optional/non-configurable one, that everybody has to 'pass' before using morphologies. If we start having options for each thing it does, it's better not to have it, and call the various checks/sanitize by hand depending on usecases (which we can still do if we want).

My understanding from the following comment: https://github.com/BlueBrain/NeuroM/pull/977#issuecomment-1021978371
was that `sanitize`, the way it is now it prevents blocks alternative workflows in which mixed trees are allowed. Otherwise, I doubt that sanitization which allows axons on dendrites would be part of the standard workflow anytime soon, if ever.

> from 2., if somebody has this flag=True in a code, forget it, and has morphologies which would crash, it would go un-noticed, and maybe the axon will disappear (or whatever may happen later). I think this new flag=True, should just convert the raise to a warning, as it is still dangerous to have such morphologies atm

Indeed. I will change it into emitting a warning when mixed trees are allowed. However, be aware of the warnings limit in `sanitize_all`
https://github.com/BlueBrain/NeuroR/blob/79b4394a79fa60f3b26f5894ff1ce44d124e8945/neuror/sanitize.py#L85-L96

**Review by adrien-berchet — DISMISSED** [review]
This is just to test my permissions, not a real approval :)

**Comment by arnaudon** [comment]
solved here in mcar: https://github.com/BlueBrain/morphology-workflows/pull/62

**Pull request closed without merging**
