### PR TITLE
Update  no soma error message in sanitize.py

### PR DESCRIPTION
**Pull request by arnaudon**

### CODE REVIEW

**Comment by arnaudon** [comment]
https://github.com/BlueBrain/NeuroR/issues/57

**Comment by wizmer** [comment]
Sorry I forgot, can you tell me how can it be existing but undefined ? thanks

**Comment by arnaudon** [comment]
retry

**Comment by arnaudon** [comment]
tough one!

**Review by wizmer — APPROVED** [review]
What a nice PR

**Comment by wizmer** [comment]
Thank you !

**Pull request merged**
