### PR TITLE
No longer check the cut plane probability

### PR DESCRIPTION
**Pull request by wizmer**
When looking for the intact axons.

This was an enhancement with the new cut plane algorithm but
it is not compatible with the legacy cut plane on which we currently
focus. The old way of computing cut points does not allow for
computing the probability than the cut plane really exists.

### CODE REVIEW

**Review by tomdele — APPROVED** [review]

**Review by mgeplf — COMMENTED** [review]
Could you add tests? I'm surprised that a change like this doesn't require a change to the test.

**Comment by mgeplf** [comment]
Ping

**Comment by wizmer** [comment]
The cut plane probability is no longer used, the only use case remaining is already tested. What would you like to see tested ?

**Comment by mgeplf** [comment]
I was surprised there wasn't a case that needed to fail due to the cut plane test failing; I guess if everything is allowed now, then there doesn't need to be a test.  Thanks.

**Pull request merged**
